# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    access_denied_url: app.default

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost:      15
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_db]
        user_db:
            entity:
                class: AppBundle:User
                property: username
        in_memory:
            memory:
                users:
                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'

    access_control:
        - { path: ^/workbench/.*, roles: ROLE_USER }
        - { path: ^/admin/.*, roles: ROLE_ADMIN }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: app.auth.login
                check_path: app.auth.login
                username_parameter: "login[username]"
                password_parameter: "login[password]"
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
            logout:
                path:   app.auth.logout
                target: app.auth.login

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER